### ISSUE TITLE
Cannot read properties of undefined (reading 'entry')

### ISSUE THREAD

**Issue by aptmac** [RedHatInsights/frontend-starter-app#592]
Hi! I'm trying to get started with this repo, and I can get other RedHatInsights/*-frontend repos to work properly. However, I'm running into issues with this repo, any help would be appreciated.

After `npm install` and `npm run start` I open the provided link in my browser and I see:
![Screenshot from 2023-09-14 16-26-15](https://github.com/RedHatInsights/frontend-starter-app/assets/10425301/ed6bb62f-c6a4-47b1-b049-9a6261cf0844)

With the error logs in my Chrome developer console looking like:

<details>
<summary>Uncaught TypeError: Cannot read properties of undefined (reading 'entry')</summary>
<pre>
    at vendors-node_modules_scalprum_core_dist_esm_index_js.eea6c27f24a971d1.js:294:105
    at step (vendors-node_modules_scalprum_core_dist_esm_index_js.eea6c27f24a971d1.js:75:23)
    at Object.next (vendors-node_modules_scalprum_core_dist_esm_index_js.eea6c27f24a971d1.js:56:53)
    at fulfilled (vendors-node_modules_scalprum_core_dist_esm_index_js.eea6c27f24a971d1.js:47:58)
</pre>
</details>

<details>
<summary>The above error occurred in the <LoadModule> component:</summary>
<pre>
at LoadModule (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_scalprum_react-core_dist_esm_index_js.5c307a00208dfb6c.js:294:17)
    at BaseScalprumComponent (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_scalprum_react-core_dist_esm_index_js.5c307a00208dfb6c.js:374:28)
    at div
    at https://stage.foo.redhat.com:1337/apps/chrome/js/src_bootstrap_tsx-src_moduleOverrides_unfetch_ts-webpack_sharing_consume_default_patternfly_r-b00be9.6e4e092c655790ff.js:5969:23
    at RenderedRoute (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_react-router-dom_dist_index_js.9707420bdaac8e39.js:5820:5)
    at Routes (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_react-router-dom_dist_index_js.9707420bdaac8e39.js:6451:5)
    at ChromeRoutes (https://stage.foo.redhat.com:1337/apps/chrome/js/src_bootstrap_tsx-src_moduleOverrides_unfetch_ts-webpack_sharing_consume_default_patternfly_r-b00be9.6e4e092c655790ff.js:14745:29)
    at div
    at main
    at div
    at Page (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_patternfly_react-core_dist_esm_components_Page_index_js.beeb52476c5c02fa.js:47:9)
    at DefaultLayout (https://stage.foo.redhat.com:1337/apps/chrome/js/src_bootstrap_tsx-src_moduleOverrides_unfetch_ts-webpack_sharing_consume_default_patternfly_r-b00be9.6e4e092c655790ff.js:19075:27)
    at https://stage.foo.redhat.com:1337/apps/chrome/js/src_bootstrap_tsx-src_moduleOverrides_unfetch_ts-webpack_sharing_consume_default_patternfly_r-b00be9.6e4e092c655790ff.js:19138:32
    at div
    at DefaultLayoutRoot (https://stage.foo.redhat.com:1337/apps/chrome/js/src_bootstrap_tsx-src_moduleOverrides_unfetch_ts-webpack_sharing_consume_default_patternfly_r-b00be9.6e4e092c655790ff.js:19188:25)
    at RenderedRoute (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_react-router-dom_dist_index_js.9707420bdaac8e39.js:5820:5)
    at Routes (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_react-router-dom_dist_index_js.9707420bdaac8e39.js:6451:5)
    at PluginStoreProvider (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_openshift_dynamic-plugin-sdk_dist_index_js.81e77255611659ea.js:1028:32)
    at ScalprumProvider (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_scalprum_react-core_dist_esm_index_js.5c307a00208dfb6c.js:480:21)
    at https://stage.foo.redhat.com:1337/apps/chrome/js/src_bootstrap_tsx-src_moduleOverrides_unfetch_ts-webpack_sharing_consume_default_patternfly_r-b00be9.6e4e092c655790ff.js:14335:25
    at div
    at DrawerContentBody (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_patternfly_react-core_dist_esm_components_Drawer_DrawerContent_js-node_m-6def4b.5b2ae9ebac202e6f.js:110:5)
    at div
    at div
    at DrawerMain (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_patternfly_react-core_dist_esm_components_Drawer_DrawerContent_js-node_m-6def4b.5b2ae9ebac202e6f.js:140:5)
    at DrawerContent (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_patternfly_react-core_dist_esm_components_Drawer_DrawerContent_js-node_m-6def4b.5b2ae9ebac202e6f.js:77:5)
    at div
    at Drawer (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_patternfly_react-core_dist_esm_components_Drawer_DrawerContent_js-node_m-6def4b.5b2ae9ebac202e6f.js:40:11)
    at HelpTopicDrawer (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_patternfly_quickstarts_dist_index_es_js.08e66923bb588452.js:2588:11)
    at HelpTopicContainer (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_patternfly_quickstarts_dist_index_es_js.08e66923bb588452.js:2569:11)
    at div
    at DrawerContentBody (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_patternfly_react-core_dist_esm_components_Drawer_DrawerContent_js-node_m-6def4b.5b2ae9ebac202e6f.js:110:5)
    at div
    at div
    at DrawerMain (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_patternfly_react-core_dist_esm_components_Drawer_DrawerContent_js-node_m-6def4b.5b2ae9ebac202e6f.js:140:5)
    at DrawerContent (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_patternfly_react-core_dist_esm_components_Drawer_DrawerContent_js-node_m-6def4b.5b2ae9ebac202e6f.js:77:5)
    at div
    at Drawer (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_patternfly_react-core_dist_esm_components_Drawer_DrawerContent_js-node_m-6def4b.5b2ae9ebac202e6f.js:40:11)
    at QuickStartDrawer (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_patternfly_quickstarts_dist_index_es_js.08e66923bb588452.js:2429:11)
    at QuickStartContainer (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_patternfly_quickstarts_dist_index_es_js.08e66923bb588452.js:2399:11)
    at ChromeProvider (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_redhat-cloud-services_chrome_esm_index_js.66de4cc3f7aca30a.js:95:23)
    at a (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_unleash_proxy-client-react_dist_index_browser_js.023bb3d7755ad782.js:9:1111)
    at FeatureFlagsProvider (https://stage.foo.redhat.com:1337/apps/chrome/js/src_components_FavoriteServices_EmptyState_tsx-src_hooks_useFavoritedServices_ts-webpack_shar-709479.b7a1e95f3afde88d.js:1230:26)
    at SegmentProvider (https://stage.foo.redhat.com:1337/apps/chrome/js/src_bootstrap_tsx-src_moduleOverrides_unfetch_ts-webpack_sharing_consume_default_patternfly_r-b00be9.6e4e092c655790ff.js:639:30)
    at Router (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_react-router-dom_dist_index_js.9707420bdaac8e39.js:6389:15)
    at HistoryRouter (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_react-router-dom_dist_index_js.9707420bdaac8e39.js:4572:5)
    at https://stage.foo.redhat.com:1337/apps/chrome/js/src_bootstrap_tsx-src_moduleOverrides_unfetch_ts-webpack_sharing_consume_default_patternfly_r-b00be9.6e4e092c655790ff.js:13903:110
    at App (https://stage.foo.redhat.com:1337/apps/chrome/js/src_bootstrap_tsx-src_moduleOverrides_unfetch_ts-webpack_sharing_consume_default_patternfly_r-b00be9.6e4e092c655790ff.js:2226:75)
    at ErrorBoundary (https://stage.foo.redhat.com:1337/apps/chrome/js/src_bootstrap_tsx-src_moduleOverrides_unfetch_ts-webpack_sharing_consume_default_patternfly_r-b00be9.6e4e092c655790ff.js:6704:9)
    at Provider (https://stage.foo.redhat.com:1337/apps/chrome/js/vendors-node_modules_react-redux_es_index_js.1d0414d586973def.js:69:3)
    at IntlProvider (https://stage.foo.redhat.com:1337/apps/chrome/js/chrome-root.e595b6f51da0dd99.js:51356:47)
</pre>
</details>

<details>
<summary>Scalprum encountered an error! Cannot read properties of undefined (reading 'entry') TypeError: Cannot read properties of undefined (reading 'entry')</summary>
<pre>
    at vendors-node_modules_scalprum_core_dist_esm_index_js.eea6c27f24a971d1.js:294:105
    at step (vendors-node_modules_scalprum_core_dist_esm_index_js.eea6c27f24a971d1.js:75:23)
    at Object.next (vendors-node_modules_scalprum_core_dist_esm_index_js.eea6c27f24a971d1.js:56:53)
    at fulfilled (vendors-node_modules_scalprum_core_dist_esm_index_js.eea6c27f24a971d1.js:47:58)
</pre>
</details>

**Comment by Hyperkid123** [comment]
This usually means the manifest file was not fetched properly or the manifest file is malformed. Let's do a quick check on what this might be about.

**Comment by Hyperkid123** [comment]
@aptmac there was a typo in a routing config file. The UI should start now with no issues.

**Comment by aptmac** [comment]
Thanks for taking a look so quickly, can confirm it's working for me now.
